import Head from 'next/head'
import React, {useContext} from 'react'
import { useRouter } from 'next/router'
import CryptoJs from 'crypto-js'
import { Input, Button, Text, Center } from '@chakra-ui/react'
import {DataContext} from '../context/GlobalState'

export default function Home() {
  //const [text, setText] = React.useState('')
  //const [cry, setCry] = React.useState('')
  //const [res, setRes] = React.useState('')
  const { state } = useContext(DataContext)
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { /**  <Input variant='filled' rounded='full' placeholder='A String' onChange={e => setText(e.target.value)} />
      <Button my={5}
      onClick={() => {
        setCry(CryptoJs.AES.encrypt(text, 'habib').toString())
      }}
       >Crypter</Button>
      {
        cry && <Text> {cry} </Text>
      }
      <Input variant='filled' rounded='full' placeholder='Result' value={res} />
      <Button my={5}
      onClick={() => {
        setRes(CryptoJs.AES.decrypt(cry, 'habib').toString(CryptoJs.enc.Utf8))
      }}
       >Decryper</Button> */}
       {
         Object.keys(state.auth).length !== 0 ?
         <Center minH='60vh' >
           <Button colorScheme='blue' >Welcome</Button>
         </Center>
         :
         <Center minH='100vh' >
           <Button colorScheme='blue' onClick={() => {
             router.push('/login')
           }} >Sign In</Button>
         </Center>
       }
    </div>
  )
}
